"""Inserindo Banco de Dados com Chave Estrangeira

Revision ID: 56ab62d9fa5f
Revises: 
Create Date: 2022-10-13 17:01:13.816584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56ab62d9fa5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carro', sa.Column('pessoa_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'carro', type_='foreignkey')
    op.create_foreign_key(None, 'carro', 'pessoa', ['pessoa_id'], ['id'])
    op.drop_column('carro', 'carro_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carro', sa.Column('carro_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'carro', type_='foreignkey')
    op.create_foreign_key(None, 'carro', 'pessoa', ['carro_id'], ['id'])
    op.drop_column('carro', 'pessoa_id')
    # ### end Alembic commands ###
